prevent rendering if readme is changed
vizhub-studio/vizhub-legacy pull request #187
Opened 2020-01-07 20:39 UTC by stushurik

The solution is based on active file name.
Theoretically, it is possible that user might change file during update, so re-run will be completed.
But I assumed that the chance of this event is low, and it is non-obvious user flow.
To avoid that case, it seems that, VizRunner component should know and keep track any change that looks as much more complicated solution.

2020-01-08 08:43 UTC, curran requested changes
Generally looks good, but it turns out that it updates whenever the active file is changed, which is not desired. Perhaps a different approach would be better, where `src/pages/VizPage/RunContext/useRun.js` is changed using an approach similar to line 37 there `const jsChanged = useRef(false);`. There could be a new thing maybe called `codeChanged`, and only if the code changed then increment the run id.

2020-01-08 08:43 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/VizRunnerContext/index.js
> +      // render frame if it is initial render or if files that might change viz were changed
Great solution! Happy that you identified and handled the case of initial render. This is the correct desired behavior.

2020-01-08 08:43 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/VizContext/index.js
> -export const VizProvider = ({ fallback, children }) => {
Good catch!

2020-01-08 13:41 UTC, stushurik commented
@curran i updated PR according to suggested solution

2020-01-11 09:20 UTC, curran approved these changes
Looks great and works well!

2020-01-11 09:20 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/RunContext/useRun.js
> +    const subscription = vizContentOp$.subscribe(({ previous, next }) => {
Surprising that this sort of thing is not caught by the linter part of create-react-app. Maybe we need to iterate on the linting setup (separate from this PR). Thanks for catching this!

2020-01-11 09:20 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/RunContext/changesJS.js
> +export const changesJS = createChangesChecker('.js');
Nice abstraction.

2020-01-11 09:20 UTC, merged