add unfurling to home page
vizhub-studio/vizhub-legacy pull request #235
Opened 2020-06-17 16:43 UTC by stushurik

2020-06-17 22:21 UTC, curran requested changes

2020-06-17 22:21 UTC, curran commented on packages/controllers/src/serveVizPage.js
> +import { servePage } from './servePage';
@stushurik This file looks like accidentally not committed?

2020-06-18 06:58 UTC, stushurik commented on packages/controllers/src/serveVizPage.js
> +import { servePage } from './servePage';
@curran which one?

2020-06-18 06:59 UTC, stushurik commented on packages/controllers/src/serveVizPage.js
> +import { servePage } from './servePage';
the diff looks like I expect

2020-06-18 14:06 UTC, curran commented on packages/controllers/src/serveVizPage.js
> +import { servePage } from './servePage';
@stushurik I see no file in the repo called `servePage`. When I check out this branch locally and try to run, this is what I see:

![image](https://user-images.githubusercontent.com/68416/85030340-55e5ab80-b14b-11ea-8332-8c91622db0b0.png)

2020-06-18 14:11 UTC, stushurik commented on packages/controllers/src/serveVizPage.js
> +import { servePage } from './servePage';
strange, looks like i didn't push one file

2020-06-18 14:20 UTC, curran requested changes
Looks great!

2020-06-18 14:20 UTC, curran commented on packages/controllers/src/servePage.js
> +export const servePage = (indexHTML, { title, description, image, url}) => {
Ahhhhh there it is! Very nice.

2020-06-18 14:21 UTC, curran approved these changes
Great - everything is there. Thanks!

2020-06-18 14:21 UTC, merged