reset warning on location change and preserve viz id on updates
vizhub-studio/vizhub-legacy pull request #268
Opened 2020-06-28 13:49 UTC by stushurik

2020-06-28 16:11 UTC, curran requested changes
I think this clears out the error a bit too aggressively.

2020-06-28 16:11 UTC, curran commented on packages/neoFrontend/src/WarningContext/index.js
> +  useEffect(() => {
Quite elegant!

But, wouldn't this also clear out the error if you close a file, or do anything within a single viz that changes the URL?

IMO as long as you continue viewing the same viz, the error should persist.

It should clear out only when you navigate between vizzes.

Maybe it could trigger here on viz ID?

2020-06-28 16:16 UTC, stushurik commented on packages/neoFrontend/src/WarningContext/index.js
> +  useEffect(() => {
@curran ok will do it more precise

2020-06-30 15:21 UTC, curran commented
This is actually fine behavior - as the change does get reverted immediately, so no need to persist the error.

If we do ever bring back the ability to edit a viz without forking it, let's revisit this.

2020-06-30 15:21 UTC, merged