Fetch data for visualization and display title
vizhub-studio/vizhub-legacy pull request #273
Opened 2020-06-30 17:05 UTC by denisemauldin

2020-07-01 08:38 UTC, stushurik commented on packages/neoFrontend/src/pages/ForksPage/index.js
> +            <Content>
huge indent

2020-07-01 08:38 UTC, stushurik commented on packages/neoFrontend/src/pages/ForksPage/usePageData.js
> +export const useVizData = () => {
would be better to have 1 hook per file

2020-07-01 08:38 UTC, stushurik commented on packages/neoFrontend/src/pages/ForksPage/usePageData.js
> +  const [data, setData] = useState(undefined);
I think better null is better when you want explicitly set that something is missing

2020-07-01 08:38 UTC, stushurik commented on packages/neoFrontend/src/pages/ForksPage/index.js
> +      className: 'test-viz-not-found',
why do you pass classname here?

2020-07-01 08:38 UTC, stushurik commented on packages/neoFrontend/src/pages/ForksPage/usePageData.js
> +    waitForSpinner(dataLoaded).then(setData);
not sure that waitForSpinner should be inside this hook, for me it looks like you mix different responsibilities into single unit 1) fetch and store data 2) adding spinner before data resolves

2020-07-01 08:38 UTC, stushurik commented on packages/neoFrontend/src/pages/ForksPage/fetchPageData.js
> +export const fetchVizPageData = async (vizId) => {
I would suggest give it more precise name like fetchViz since it's not fetch all page data but only viz that is used for title

2020-07-01 08:38 UTC, stushurik commented on packages/neoFrontend/src/pages/ForksPage/usePageData.js
> +  useEffect(() => {
since now we have 2 hooks i would recommend rename it to something like useForks and useViz

2020-07-01 15:29 UTC, curran commented on packages/neoFrontend/src/pages/ForksPage/index.js
> +            <Content>
@denisemauldin There is a setup for Prettier - you can run `yarn prettier` inside the `neoFrontend` directory to auto-format the code. Now that I think of it, this note would make a great addition to the README for future new VizHub developers.

2020-07-01 15:29 UTC, curran commented on packages/neoFrontend/src/pages/ForksPage/index.js
> +      className: 'test-viz-not-found',
I think it's a copy of a pattern found elsewhere in the codebase.

2020-07-01 15:40 UTC, curran requested changes
@denisemauldin I'm thrilled that this works! However, I want to suggest an alternative that is more in line with the architecture of VizHub, which is roughly [Clean Architecture](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html).

The notion is that there should be an "interactor" that is responsible for gathering all data needed for this page. This page can then make a single network request for all its data (not multiple as your implementation currently does).

I suggest to please try the following:
 * Remove the `fetchVizPageData` setup here. While this does work, it actually fetches more data than required, as that endpoint (and interactor) is tailored to feed into the viz page.
 * Create a new file `useCases/src/interactors/getForksPageData.js`
 * Implement it such that it composes the existing interactors `useCases/src/interactors/getForks.js` and `useCases/src/interactors/getVisualizationInfo.js` (invoking the `GetVisualizationInfo` interactor is a much lighter-weight way of getting the data you need to render the title than invoking the `fetchVizPageData` endpoint).
 * Modify `controllers/src/apiController/visualizationAPIController/getForksController.js` to invoke this new interactor.
 * In the front end code, just unpack the vizInfo data from the existing response and use it.

Thanks for this work. Good luck!

2020-07-12 01:31 UTC, denisemauldin commented
I updated to use the interactor, but I'm unsure how to test these changes.  Can you provide instructions?

I updated `packages/database/src/getVisualizationInfo.js` to return an error if the ID wasn't found because the console was throwing a `Cannot read property 'id' of undefined` when the visualization did not exist.

2020-07-12 01:41 UTC, denisemauldin commented
I could not figure out how the routing worked to go from `/api/visualization/get/${vizId}/forks?offset=${offset}` to the appropriate controller or how `vizhub-use-cases` magic works.  Is there any documentation on that?

2020-07-13 14:57 UTC, curran commented
Apologies, there is no documentation for it. Will review this tomorrow. Thanks for this work!

2020-07-15 15:22 UTC, curran approved these changes
Looks great! Will merge then refine.

Thank you @denisemauldin for this work.

2020-07-15 15:22 UTC, merged