enable linter for javacript
vizhub-studio/vizhub-legacy pull request #318
Opened 2020-07-23 13:26 UTC by stushurik

Closes datavis-tech/vizhub-issue-tracker/issues/157
Closes datavis-tech/vizhub-issue-tracker/issues/389

2020-07-23 14:18 UTC, curran approved these changes
Amazing!

The linting rules setup needs more iteration, but I'd like to merge this.

I think I will add some commits here to put the feature behind a feature flag, so we can have it in staging for a while before deploying to production.

2020-07-23 14:18 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/Body/Editor/CodeEditor/CodeArea/CodeAreaCodeMirror5/CodeMirrorLintCSS.js
> +    url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sJDw4cOCW1/KIAAAAZdEVYdENvbW1lbnQAQ3JlYXRl
I'm curious where did these come from? If from an external reference, I like to keep the URLs in the code comments for future reference.

2020-07-23 14:18 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/Body/Editor/CodeEditor/CodeArea/CodeAreaCodeMirror5/CodeMirrorLintCSS.js
> +    url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAYAAAC09K7GAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sJDw4cOCW1/KIAAAAZdEVYdENvbW1lbnQAQ3JlYXRl
Looks like from https://codemirror.net/demo/lint.html

2020-07-23 14:20 UTC, curran commented
We need to add the React plugin I think, so it recognizes JSX.

![image](https://user-images.githubusercontent.com/68416/88297602-1708bf80-ccce-11ea-9a20-4046ae509d6e.png)

Can be done in a later PR.

2020-07-23 14:23 UTC, curran commented
Also we need to make sure it does not conflict with Prettier - there's a thing for this https://github.com/prettier/eslint-plugin-prettier

Another consideration is bundle size. I'm curious how large is the `eslint4b` dependenciy in terms of KBs loaded. Ideally this could be loaded after all other editor modules are loaded, but not sure if this is practical. At least I'd like to compare bundle sizes before and after this change.

2020-07-23 14:31 UTC, curran commented
Deployed this to staging to try it out.

Size difference is 1.7 MB. We should definitely load this async for progressive enhancement.

Details:
 * 4.3 MB resources `https://staging.vizhub.com/curran/81e306c23cd2497f920d42c9e7422c21?edit=files&file=index.js`
 * 2.6 MB resources `https://vizhub.com/curran/81e306c23cd2497f920d42c9e7422c21?edit=files&file=index.js`

2020-07-23 14:40 UTC, curran requested changes
Actually @stushurik Do you think you could please take another pass at this, to address the following:
 * Load the ESLint module async, after the core CodeMirror modules.
 * Enable ESLint behind a feature flag driven from an environment variable (similar to NeoNav).
 * If the feature flag is disabled, the ESLint module should not be loaded. This is so production site does not get the additional KBs until the feature is enabled there.

Thanks!

2020-07-28 14:08 UTC, stushurik commented
@curran i added feature flag and made it async. But it is hard to add plugins. The problem is that eslint accepts plugin names and tries get them from node_modules which does not work in our case. Moreover plugins code is not compatible with browsers so we need either 1) create our own copies of required plugins or 2) adjust webpack config so that it transpiles plugins code.
I propose add simple custome rule or global variable that ignores React and adjust rules manually so that they don't conflict with prettier. More advanced changes could be done in future

2020-07-28 14:13 UTC, curran commented
I see this demo supports JSX https://eslint.org/demo

![image](https://user-images.githubusercontent.com/68416/88676937-ae995400-d0ba-11ea-9de8-87bfcca943d9.png)

Maybe there are no plugins required for us, just a specific configuration of rules.

I think some plugins are just sets of rules anyway.

The plugins/config I'd like to emulate is pretty much the same config we are using for the VizHub codebase itself, found in `vizhub/.eslintrc.js`.

These are just initial thoughts. Will review now in detail.

2020-07-28 14:14 UTC, stushurik commented
@curran i already enabled jsx. it's not the same as react

2020-07-28 14:16 UTC, stushurik commented
@curran i tried to import eslint-plugin-react and merge fed it to browser linter, but it is full of `require` which is not work in browser

2020-07-28 14:53 UTC, curran commented
@stushurik I opened an issue in `eslint-plugin-react` for a browser build https://github.com/yannickcr/eslint-plugin-react/issues/2732 If you get a chance, could you please drop the errors you saw into that issue? Thanks!

2020-07-28 19:16 UTC, stushurik commented
@curran now i don't understand how to finish this pr

2020-07-30 16:27 UTC, curran approved these changes
This looks great to merge. A great step forward in the right direction.

Will look at iterating and enabling at first just a few linting rules. 

Over time we can evolve it to support more things, like CSS and React hooks.

2020-07-30 16:27 UTC, curran commented on packages/neoFrontend/package.json
> +    "eslint4b": "^7.5.0",
This library looks OK, but it's sort of not very strong in terms of adoption. I hesitate to take on new dependencies. I'm curious what it might take to get it working without this. Perhaps not possible, but I'm curious.

2020-07-30 16:27 UTC, curran commented on packages/neoFrontend/src/pages/ProfilePage/Body/styles.js
> +export const ProfileMenuBar = styled(Centering)`
Looks good but seems unrelated to linting. In future it would be great to separate PRs more for different features.

2020-07-30 16:27 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/Body/Editor/CodeEditor/CodeArea/CodeAreaCodeMirror5/CodeMirrorLintCSS.js
> +    background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAcAAAAHCAMAAADzjKfhAAAACVBMVEUAAAAAAAC/v7914kyHAAAAAXRSTlMAQObYZgAAACNJREFUeNo1ioEJAAAIwmz/H90iFFSGJgFMe3gaLZ0od+9/AQZ0ADosbY
Ya this is cool! In future could replace with custom icons here.

2020-07-30 16:27 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/Body/Editor/CodeEditor/CodeArea/CodeAreaCodeMirror5/index.js
> +      lint: lintJs,
Interesting that CodeMirror has an API for this specifically. Trying to understand if this is handled buy CodeMirror itself or by some linting plugin...

2020-07-30 16:27 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/EditorModulesContext/editorModules.js
> -//import 'codemirror/addon/wrap/hardwrap';
Nice cleanup.

2020-07-30 16:27 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/EditorModulesContext/codemirrorAddons/lint/jsxLint.js
> +  const linterModulePromise = import('eslint4b');
Nice work making this import dynamic!

2020-07-30 16:27 UTC, merged