Google and Facebook Auth Phase I
vizhub-studio/vizhub-legacy pull request #345
Opened 2020-08-15 17:01 UTC by kalpesh05

Initially added package for google login to check what data comes and how we can use also made back-end function to get user basic detail by id_token  , figuring out how to integrate google auth in recent flow

Note: After finalization code will change for google auth , it's just for check

2020-08-17 17:00 UTC, stushurik requested changes
please run prettier cause this PR mess up formatting

2020-08-17 17:00 UTC, stushurik commented on package.json
> +  "dependencies": {}
if you didn't add dependencies please remove it

2020-08-17 17:00 UTC, stushurik commented on packages/controllers/src/jwtAuth/getFBUser.js
> +};
this } is redundant here

2020-08-17 17:00 UTC, stushurik commented on packages/controllers/src/jwtAuth/getFBUser.js
> +if (FBUser.error) {
bad indent, please run prettier

2020-08-17 17:00 UTC, stushurik commented on packages/controllers/src/jwtAuth/getFBUser.js
> +  const response = await fetch(`${FBGetUserInfoUrl}${token}`, fetchOptions);
you can use embeded http package https://nodejs.org/api/http.html instead of adding node-fetch to project

2020-08-17 17:00 UTC, stushurik commented on packages/controllers/src/jwtAuth/getGitHubUser.js
> +import fetch from "node-fetch";
please use single quotes (quotes should be the same across all project) or run prettier

2020-08-17 17:00 UTC, stushurik commented on packages/controllers/src/jwtAuth/getGitHubUser.js
> +import fetch from "node-fetch";
use https://nodejs.org/api/http.html

2020-08-17 17:00 UTC, stushurik commented on packages/controllers/src/jwtAuth/getFBUser.js
> +const FBGetUserInfoUrl = `https://graph.facebook.com/v8.0/me?fields=id,name,first_name,last_name,picture&access_token=`;
this const does not follow const naming it should be fbGetUserInfoUrl, check out
```
const gitHubUserURL = "https://api.github.com/user";
```

2020-08-17 17:00 UTC, stushurik commented on packages/serverGateways/src/shareDB.js
> +console.log("process.env.VIZHUB_MONGO_URI", process.env.VIZHUB_MONGO_URI);
please remove console log

2020-08-17 17:00 UTC, stushurik commented on packages/serverGateways/src/shareDB.js
> +import redis from "redis";
please bring back formating (do not mix quotes and use commas)
please use prettier

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/pages/AuthPopupPage/index.js
> +  // console.log();
remove this line

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/pages/AuthPopupPage/index.js
> +        // console.log(data);
remove this line

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/pages/AuthPopupPage/index.js
> +    if (code) {
i would suggest refactor it to it's own hook

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/pages/AuthPage/index.js
> +              <br />
use css padding/margin to achieve space between elements instead of multiple br tags

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/pages/AuthPage/index.js
> +              {process.env.NODE_ENV === "development" ? (
bring back single quotes

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/pages/AuthPopupPage/index.js
> +      getJWT(code).then(data => {
this to blocks of similar, you just call different function so i think you can make it without duplicating code

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/pages/AuthPage/index.js
> +  // getJWTForGoogle,
remove this line

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/authentication/signInFlow/listenForMe.js
> +export const listenForMe = onMeReceived => {
bring back single quotes

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/authentication/postMessageToOpener.js
> +  console.log(vizHubAuthenticatedUser);
remove this line

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/authentication/index.js
> +export { AuthContext, AuthProvider } from "./AuthContext";
bring back single quotes

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/authentication/getJWTForGoogle.js
> +// const url = () => {
remove it

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/authentication/getJWTForGoogle.js
> +  const response = await fetch(`/api/auth/google`, {
you dont need backtick ` here.

2020-08-17 17:00 UTC, stushurik commented on packages/neoFrontend/src/authentication/getJWT.js
> +import { CI_USER_CODE } from "./constants";
bring back single quotes

2020-08-17 17:00 UTC, stushurik commented on packages/controllers/src/jwtAuth/routes/authGoogle.js
> +export const authGoogle = userGateway => {
a lot of duplicating code.
code looks almost similar to packages/controllers/src/jwtAuth/routes/authGitHub.js
you can create generic controller and use it multiple times

2020-08-18 12:35 UTC, curran commented on packages/controllers/src/jwtAuth/getFBUser.js
> +const FBGetUserInfoUrl = `https://graph.facebook.com/v8.0/me?fields=id,name,first_name,last_name,picture&access_token=`;
Agree - lower case starting letters for variables that are not React components.

2020-08-18 12:36 UTC, curran commented on packages/neoFrontend/src/pages/AuthPage/index.js
> +              <br />
Agree.

2020-08-18 12:37 UTC, curran commented on packages/neoFrontend/src/authentication/postMessageToOpener.js
> +  console.log(vizHubAuthenticatedUser);
Agree.

2020-08-18 12:38 UTC, curran commented on packages/controllers/src/jwtAuth/routes/authGoogle.js
> +export const authGoogle = userGateway => {
Agree. Where possible, please refactor code into common modules instead of duplicating. Maybe duplicate as a first pass, then refactor as a clean up pass. But both can land in a single PR.

2020-08-18 13:00 UTC, curran requested changes
Great effort here! Happy to see this progress, but lots more to do for cleaning this up. Please address the feedback here and add more commits to this PR, we will review it again. Thanks!

2020-08-18 13:00 UTC, curran commented on packages/controllers/src/jwtAuth/getFBAccessToken.js
> +const oAuthAccessTokenURL = `https://graph.facebook.com/v8.0/oauth/access_token?client_id=392704021076365&redirect_uri=http://localhost:3000/authenticated&client_secret=13aedfb953666b2a425e5ba00deef3
Please derive the client ID here from an environment variable. For example `REACT_APP_VIZHUB_FACEBOOK_CLIENT_ID`.

2020-08-18 13:00 UTC, curran commented on packages/controllers/src/jwtAuth/getFBAccessToken.js
> +const oAuthAccessTokenURL = `https://graph.facebook.com/v8.0/oauth/access_token?client_id=392704021076365&redirect_uri=http://localhost:3000/authenticated&client_secret=13aedfb953666b2a425e5ba00deef3
Also please derive client secret from a new environment variable `VIZHUB_FACEBOOK_CLIENT_SECRET`. Note that the prefix `REACT_APP_` makes an environment visible to client-side code, so it's important that this one does _not_ have it. Thanks!

2020-08-18 13:00 UTC, curran commented on packages/controllers/src/jwtAuth/getFBAccessToken.js
> +        "Check that you have your GitHub OAuth environment variables set"
```suggestion
        "Check that you have your Facebook OAuth environment variables set"

```

2020-08-18 13:00 UTC, curran commented on packages/controllers/src/jwtAuth/getFBUser.js
> +// Documentation: https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint
It's great to add these links! Nice work including this for reference.

2020-08-18 13:00 UTC, curran commented on packages/controllers/src/jwtAuth/getFBUser.js
> +  const response = await fetch(`${FBGetUserInfoUrl}${token}`, fetchOptions);
I believe `node-fetch` may have already been a dependency before this. It was already in use in `getGitHubUser` from earlier. I'm fine with this package, mainly for developer sanity in using the same `fetch` API in both client and server.

2020-08-18 13:00 UTC, curran commented on package.json
> +  "dependencies": {}
I wonder did this get here automatically? Agree, let's remove it if it's not required.

2020-08-18 13:00 UTC, curran commented on packages/controllers/src/jwtAuth/routes/authGoogle.js
> +      res.cookie("vizHubJWT", vizHubJWT, { httpOnly: true, maxAge: 14 * days });
This logic is duplicated several times and would benefit from being unified into a single definition. Please do that refactoring as part of this PR. Thanks!

2020-08-18 13:00 UTC, curran commented on packages/neoFrontend/src/authentication/constants.js
> +// Both Google and FB client need to make adynamic from env after test
Please address this TODO. Good idea!

2020-08-18 13:00 UTC, curran commented on packages/neoFrontend/src/authentication/getJWTForGoogle.js
> +  const response = await fetch(`/api/auth/google`, {
Agree. This might even give a linting error. I have my Vim set up with ESLint plugin so it's very clear to fix these sorts of things. I wonder @kalpesh05 if you could enable whatever IDE you are using to show ESLint errors based on our ESLint configuration. That would be very useful.

2020-08-18 13:00 UTC, curran commented on packages/neoFrontend/src/pages/AuthPage/index.js
> +                <Button>Sign in with FaceBook</Button>
```suggestion
                <Button>Sign in with Facebook</Button>
```

2020-08-18 13:00 UTC, curran commented on packages/serverGateways/src/shareDB.js
> +console.log("process.env.VIZHUB_MONGO_URI", process.env.VIZHUB_MONGO_URI);
Agree.

2020-08-18 13:00 UTC, curran commented on packages/neoFrontend/package.json
> +    "react-google-login": "^5.1.21",
Please remove this, as it's not being used anywhere (which is a good thing). Happy we can get it to work without a high-level new dependency like this!

2020-08-20 14:20 UTC, stushurik requested changes

2020-08-20 14:20 UTC, stushurik commented on packages/controllers/src/jwtAuth/common.js
> +export const config = {
you don't need keep all configs in single place in this case.
you can keep config related to each company near to code that handle request for each and than pass config object

2020-08-20 14:20 UTC, stushurik commented on packages/controllers/src/jwtAuth/common.js
> +export const config = {
actually i think this is bad case of generalization.

2020-08-20 14:20 UTC, stushurik commented on packages/serverGateways/src/shareDB.js
> -
please bring back empty line between const and function

2020-08-20 14:20 UTC, stushurik commented on packages/neoFrontend/src/pages/AuthPopupPage/index.js
> +    if (code) {
still not refactored, i suggest:
```javascript
// should be in its own file
const useOpener = (getTokenFn) => {
 const [error, setError] = useState(null)

  useEffect(() => {
    if (id_token) {
      getTokenFn().then((data) => {
        if (data.error) {
          setError(new Error(data.errorDescription));
        } else {
          postMessageToOpener(data);
        }
      });
    }
  }, [getTokenFn, setError]);

  return error;
}

// should be in its own file
const useTokenGetter = () => {
  const { search, hash } = useLocation() // import { useLocation } from 'react-router';
  const { code } = queryString.parse(search);
  const { id_token } = queryString.parse(hash);
  
   return useMemo(() => {
     if (code) {
        return getJWT.bind(null, code)
     }

    if (id_token) {
        return getJWTForGoogle.bind(null, id_token)
    }
         
  }, [code, id_token])
}

// packages/neoFrontend/src/pages/AuthPopupPage/index.js
...

const getTokenFn = useTokenGetter()
const error = useOpener(getTokenFn)

if (error) {
  // handle error
} else {
  // success case
}
...
```

2020-08-20 14:20 UTC, stushurik commented on packages/neoFrontend/src/pages/AuthPage/index.js
> +              <a href={GOOGLE_OAUTH_URL} style={{ paddingTop: '5%' }}>
don't use style attr, create styled component

2020-08-20 14:20 UTC, stushurik commented on packages/neoFrontend/src/authentication/getJWTForGoogle.js
> +export const getJWTForGoogle = async (code) => {
this function looks like exactly the same as https://github.com/curran/vizhub/pull/345/files#diff-30ed96b8421a644d2412e9f0364ec98aR9 except url.

2020-08-20 14:20 UTC, stushurik commented on packages/neoFrontend/src/authentication/getJWTForGoogle.js
> +export const getJWTForGoogle = async (code) => {
make that function parametric

2020-08-20 14:20 UTC, stushurik commented on packages/neoFrontend/src/authentication/constants.js
> +export const GOOGLE_OAUTH_URL = `https://accounts.google.com/o/oauth2/auth?scope=email profile openid&openid.realm&client_id=${GOOGLE_CLIENT_ID}&redirect_uri=http://localhost:3000/authenticated&respo
those constant contain localhost:3000 this is wrong for prod and staging

2020-08-20 14:20 UTC, stushurik commented on packages/neoFrontend/package.json
> +    "react-google-login": "^5.1.21",
and don't forget to revert back package-json.lock cause you did not introduce new packages

2020-08-20 14:20 UTC, stushurik commented on packages/controllers/src/jwtAuth/routes/auth.js
> +      let token =
instead of introducing more conditions i suggest to have as much routes as auth providers.
in our case there are would be 3 routes at the moment: github, facebook and google.
But they should be slim and use some common logic:
```javascript

// google route

const getUserFromRequest = (request) => {
  // do google specific stuff in order retrieve user data from request 
  // and return user in vizhub format
   return user;
} 

export const auth = createAuthController(getUserFromRequest)

// createAuthController looks like:
const createAuthController = (getUserFromRequest) => {
  return (userGateway) => {
     // the same function body as current packages/controllers/src/jwtAuth/routes/auth.js except:
    const oAuthProfile = getUserFromRequest(request);
    // rest of code
  }
}

// for facebook and github looks similar, you just need implement getUserFromRequest for each case
```

2020-08-20 14:20 UTC, stushurik commented on packages/controllers/src/jwtAuth/getUser.js
> +export const getUser = async (type, accessToken) => {
remove this file, check out my comment in packages/controllers/src/jwtAuth/routes/auth.js

2020-08-20 14:20 UTC, stushurik commented on packages/controllers/src/jwtAuth/common.js
> +export const config = {
remove this file, check out my comment in packages/controllers/src/jwtAuth/routes/auth.js

2020-08-20 18:28 UTC, curran commented
Thank you @stushurik for reviewing! The comments all look good. Another round of revisions is required. It's getting there.

I'd like to merge this PR as soon as review comments have been addressed, but then temporarily disable the login buttons behind a feature flag. Currently the ID used to resolve the user is dependent on the auth provider. So, if the same person authenticates via two providers, that person will end up with two distinct VizHub User entries. Resolving the user based on email ID should solve this. That can be done in a subsequent PR.

2020-08-21 12:12 UTC, curran requested changes
Hi @kalpesh05 , I have reviewed this again. This time I have added many "suggestions", which you can just click "commit suggestion" to commit. I hope the feedback is actionable and it is clear what to do next to finalize this PR. It's almost there!

2020-08-21 12:12 UTC, curran commented on README.md
> +export REACT_APP_VIZHUB_GOOGLE_CLIENT_ID=1089209754756-iuvb60rkf8mheiqk186n3kk7lp6sb5kr.apps.googleusercontent.com
Here we can also document Facebook environment variable.

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/common.js
> +      break;
This could be `return` directly. No need for `obj` variable.

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/common.js
> +      break;
Same thing here - just `return` the literal. No need of `userobj` variable.

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/getAccessToken.js
> +      ? config[`${type}`]['oAuthAccessTokenURL']
```suggestion
      ? config[type].oAuthAccessTokenURL
```

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/getAccessToken.js
> +      ? config[`${type}`]['oAuthAccessTokenURL']
You can just click "Commit suggestion" for these - it's a cool GitHub feature.

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/getAccessToken.js
> +      : `${config[`${type}`]['oAuthAccessTokenURL']}${code}`;
This line looks like possibly invalid, definitely confusing, JavaScript.

```suggestion
      : config[type].oAuthAccessTokenURL + code;
```

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/getAccessToken.js
> +    let error = errorObj(type, data);
Prefer `const` if there is no reassignment.

```suggestion
    const error = errorObj(type, data);
```

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/getUser.js
> +  let getUserUrl =
```suggestion
  const getUserUrl =
```

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/getUser.js
> +    let error = errorObj(type, user);
```suggestion
    const error = errorObj(type, user);
```

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/routes/auth.js
> +    let { type } = req.params;
```suggestion
    const { type } = req.params;
```

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/routes/auth.js
> +      let token =
```suggestion
      const token =
```

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/routes/auth.js
> +      let token =
Agree it's a good idea. I want to get this PR merged soon also. Perhaps this can be a follow-up refactoring PR.

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/routes/auth.js
> +      //   // Generate a JWT with the user id as its payload.
```suggestion
      // Generate a JWT with the user id as its payload.
```

2020-08-21 12:12 UTC, curran commented on packages/controllers/src/jwtAuth/routes/auth.js
> +      //   // Store the JWT securely in an httpOnly cookie.
```suggestion
      // Store the JWT securely in an httpOnly cookie.
```

2020-08-21 12:12 UTC, curran commented on packages/neoFrontend/package.json
> +    "react-google-login": "^5.1.21",
Indeed. Please do remove this package and revert package-lock.json. Thanks!

2020-08-21 12:12 UTC, curran commented on packages/neoFrontend/src/authentication/constants.js
> +export const FACEBOOK_OAUTH_URL = `https://www.facebook.com/v8.0/dialog/oauth?client_id=392704021076365&response_type=code&redirect_uri=http://localhost:3000/authenticated&state="{viz-2@#A}"`;
Please do also move the Facebook client ID to an environment variable.

```suggestion
export const FACEBOOK_OAUTH_URL = `https://www.facebook.com/v8.0/dialog/oauth?client_id=${FACEBOOK_CLIENT_ID}&response_type=code&redirect_uri=http://localhost:3000/authenticated&state="{viz-2@#A}"`;
```

2020-08-21 12:12 UTC, curran commented on packages/neoFrontend/src/authentication/getJWT.js
> +  let type = isCI ? 'ci' : code && code.length > 20 ? 'fb' : 'github';
```suggestion
  const type = isCI ? 'ci' : code && code.length > 20 ? 'fb' : 'github';
```

2020-08-21 12:12 UTC, curran commented on packages/neoFrontend/src/authentication/getJWT.js
> +  let type = isCI ? 'ci' : code && code.length > 20 ? 'fb' : 'github';
The `code.length > 20` logic is a bit confusing. I'm not sure why this works.

2020-08-21 12:12 UTC, curran commented on packages/neoFrontend/src/authentication/getJWTForGoogle.js
> +export const getJWTForGoogle = async (code) => {
Agree. Can also be done in a second pass.

2020-08-21 12:12 UTC, curran commented on packages/neoFrontend/src/pages/AuthPage/index.js
> +              <a href={GOOGLE_OAUTH_URL} style={{ paddingTop: '5%' }}>
I can do this when I take a pass at putting these behind a feature flag.

2020-08-21 12:12 UTC, curran commented on packages/neoFrontend/src/pages/AuthPopupPage/index.js
> +  const { id_token } = queryString.parse(window.location.hash);
No need to call `queryString.parse` twice. I suggest:

```suggestion
  const { code, id_token } = queryString.parse(window.location.hash);
```

2020-08-21 12:12 UTC, curran commented on packages/neoFrontend/src/pages/AuthPopupPage/index.js
> +    if (code) {
Indeed. @kalpesh05 Please try dropping in this code from @stushurik . Thanks!

2020-08-22 05:03 UTC, kalpesh05 commented
i have made some changes, remove that common.js/getuser.js file and did route identification via state parameter which we get with code/id_token

2020-08-22 14:06 UTC, curran commented on packages/controllers/src/jwtAuth/getAccessToken.js
> +      body: JSON.stringify({ client_id, client_secret, code }),
Aha! This looks like the solution to the errors we were looking at. I will try changing it back to the way it was. `body` is not part of the header.

2020-08-22 14:10 UTC, curran commented on packages/controllers/src/jwtAuth/getAccessToken.js
> +      body: JSON.stringify({ client_id, client_secret, code }),
Yes, that solved it.

2020-08-22 14:18 UTC, curran commented on README.md
> +export REACT_APP_VIZHUB_REDIRECT_URI=http://localhost:3000/authenticated
@kalpesh05 I had a thought - rather than using `state` to know what provider the redirect goes to, we could have different routes. For example `http://localhost:3000/authenticated/github`, `http://localhost:3000/authenticated/facebook`, `http://localhost:3000/authenticated/google`. Do you think that would work? It might be a cleaner way to do it, if we can avoid having that `state` field.

2020-08-22 14:19 UTC, curran commented on packages/controllers/src/jwtAuth/getFBUser.js
> +  let fetchOptions = {
```suggestion
  const fetchOptions = {
```

2020-08-22 14:21 UTC, curran commented on packages/controllers/src/jwtAuth/routes/authMe.js
> +      console.log(id);
```suggestion

```

2020-08-22 14:22 UTC, curran commented on packages/neoFrontend/src/authentication/constants.js
> +export const GITHUB_OAUTH_URL = `${OAUTH_URL_BASE}?client_id=${GITHUB_CLIENT_ID}&state=${stateEncoder(
Maybe in next PR we can remove `state`.

2020-08-22 14:23 UTC, curran commented on packages/neoFrontend/src/authentication/postMessageToOpener.js
> +  console.log(window.opener.location);
```suggestion
```

2020-08-22 14:23 UTC, curran commented on packages/neoFrontend/src/pages/AuthPage/styles.js
> +export const SinginLink = styled.a`
Very nice change! Thanks for doing this.

2020-08-22 14:30 UTC, merged