add deps auto-injection
vizhub-studio/vizhub-legacy pull request #361
Opened 2020-10-04 15:24 UTC by stushurik

2020-10-05 14:17 UTC, curran requested changes
Really great start! Please use the presence of `package.json` as the thing that enables this new code path. Thanks!

2020-10-05 14:17 UTC, curran commented on packages/presenters/src/computeSrcDoc.js
> +const parser = new DOMParser();
Nice. Yes, this is the same approach I would have taken.

2020-10-05 14:17 UTC, curran commented on packages/presenters/src/computeSrcDoc.js
> +  const indexHtml = injectDependenciesScript(injectBundleScript(htmlTemplate), files);
At this point here, there should be a check "Does `package.json` exist?". If so, this code should run, otherwise the old logic should run. That's the only main feedback I have. Otherwise looks like a really great start!

2020-10-07 10:55 UTC, stushurik commented on packages/presenters/src/computeSrcDoc.js
> +  const indexHtml = injectDependenciesScript(injectBundleScript(htmlTemplate), files);
It does not change\break current vizzes, cause:
1) If index.html has script with src="bundle.js" it does not inject it and just return indexHtml as is
2) If there is no package.json or there is no dependencies it does not modify indexHtml

2020-10-07 11:00 UTC, stushurik commented on packages/presenters/src/computeSrcDoc.js
> +  const indexHtml = injectDependenciesScript(injectBundleScript(htmlTemplate), files);
Do you still want do some modifications?

2020-10-07 11:45 UTC, curran approved these changes
Very nice. Thanks for adding the short-circuit case.

I think I was just confused - I thought it would attempt to inject `bundle.js` even if it wasn't present.

This looks great now with the recent commit.

2020-10-07 11:45 UTC, curran commented on packages/presenters/src/computeSrcDoc.js
> +  if (deps.length === 0) return htmlTemplate;
Nice. This is the sort of short-circuiting I was hoping to see. This is great.

2020-10-07 11:48 UTC, curran commented on packages/presenters/src/computeSrcDoc.js
> +    return pkg.dependencies || {};
It would be great to add some unit tests for just this function. I can see it handles several specific cases, it woud be great to have those mapped out.

2020-10-07 11:49 UTC, merged