Feature/snippets
vizhub-studio/vizhub-legacy pull request #382
Opened 2020-11-12 16:40 UTC by stushurik

2020-11-12 22:49 UTC, curran approved these changes
Looks great so far!

I just read through the code. I hope to do a deeper review tomorrow and run it locally.

2020-11-12 22:49 UTC, curran commented on packages/neoFrontend/src/utils/number.js
> +    return xorSwap(rangeBoundariesString.split('-'));
xorSwap is kind of cool, but is it really necessary? Would a simple `.reverse()` do the same thing? Performance is not a concern at all here, just doing this once.

```suggestion
    return rangeBoundariesString.split('-').reverse();
```

2020-11-12 22:49 UTC, curran commented on packages/neoFrontend/src/utils/number.js
> +const isFiniteNumber = (n) => Boolean(isFinite(n) && !isNaN(parseFloat(n)));
Nice defensive validation.

2020-11-12 23:41 UTC, stushurik commented on packages/neoFrontend/src/utils/number.js
> +    return xorSwap(rangeBoundariesString.split('-'));
xorSwap is smart reverse, if range is 10,20 (asc order) it returns 10,20(stays same), if range is 20,10 (desc order) it returns 10,20 (do reverse)

2020-11-13 10:19 UTC, stushurik commented on packages/neoFrontend/src/utils/number.js
> +    return xorSwap(rangeBoundariesString.split('-'));
I saw it in the example I was inspired by. And at that moment i liked it, but now I think xorSwap is not a good name cause its not obvious what it does

2020-11-13 13:38 UTC, curran commented on packages/neoFrontend/src/utils/number.js
> +    return xorSwap(rangeBoundariesString.split('-'));
Ah I see! That's cool. I'm fine to keep it in that case. It was not clear to me that that's what it does. Maybe a comment would be good to add about that. 
```suggestion
    // xorSwap is smart reverse, if range is 10,20 (asc order) it returns 10,20(stays same), if range is 20,10 (desc order) it returns 10,20 (do reverse)
    return xorSwap(rangeBoundariesString.split('-'));
```

2020-11-13 13:57 UTC, curran requested changes
Review comments from QA on https://staging.vizhub.com/curran/7e303867f6764667a45081958825925f?edit=files&file=index.html&line :

 * Linking to line number appears broken now. When clicking a line number, nothing happens.
 * When navigating to the snippet tab, nothing is pre-filled, making it diffucult to get it to work. It would be great to pre-fill all form field values, so the user can start tweaking them instead of trying to figure out what to do to get something to show up. Suggest to default to `index.html` with first 5 lines highlighted.
 * The field "Choose which lines to include into snippet *(requried)" appears to do nothing.
 * The embedded view shows the viewer and top bar.

![image](https://user-images.githubusercontent.com/68416/99079539-169e7800-258e-11eb-9430-f9ab86b6e1b3.png)

Clicking the "fullscreen" button on the editor and the up arrow gets us pretty close to where we want to be.

![image](https://user-images.githubusercontent.com/68416/99079621-32098300-258e-11eb-8b9f-6f0f903b2835.png)

2020-11-13 14:21 UTC, stushurik commented
@curran you saw wrong/broken snippet cause snippet link lead to prod instead of staging.
I pushed a fix, check it again please

2020-11-13 15:18 UTC, curran commented
@stushurik I just deployed the latest commit to staging, and the behavior is the same.

More detail: the interaction of clicking on the line number is broken. To reproduce: open the editor, click on a line number.
 * Current behavior with this PR: nothing happens.
 * Expected behavior (in production currently): line number highlights and blinks, and the URL is updated.

2020-11-13 16:30 UTC, curran commented
@stushurik This might be a solution for scrolling to center https://stackoverflow.com/questions/10575343/codemirror-is-it-possible-to-scroll-to-a-line-so-that-it-is-in-the-middle-of-w

You can use the average of the start and end to get the line to center on.

2020-11-16 19:32 UTC, curran approved these changes
Code changes look great! I put it on staging.

Room for improvement for sure, but this is good enough as a first pass.

I will merge this and create follow-up issues.

In the mean time, we can start testing it out in actual posts and see what the pain points are.

2020-11-16 19:32 UTC, curran commented on packages/neoFrontend/src/pages/VizPage/URLStateContext/useURLState.js
> +  const onHideViz = () => setMode(modes.hide);
Nice organization.

2020-11-16 19:32 UTC, curran commented on packages/neoFrontend/src/utils/number.js
> +// inspired by https://codereview.stackexchange.com/questions/26125/getting-all-number-from-a-string-like-this-1-2-5-9
Nice. Great to include these URLs.

2020-11-16 19:32 UTC, curran commented on packages/neoFrontend/src/utils/number.js
> +    String(sequenceString)
I think it's guaranteed to already be a String, so no need to pass into the `String` constructor?
```suggestion
    sequenceString
```

2020-11-16 19:34 UTC, merged