feat: ability to compile svelte files
vizhub-studio/vizhub-legacy pull request #393
Opened 2020-12-03 12:55 UTC by milafrerichs

WIP and POC of getting rollup to compile svelte files
the tests is failing to show the output

2020-12-03 13:02 UTC, stushurik commented on packages/presenters/src/bundle.js
> +import svelte from './svelte';
it looks like that it would always load svetle lib into browser. not all vizzes require svetle. we need to think how to load svetle only for svetle-based vizzes

2020-12-03 13:04 UTC, stushurik commented on packages/presenters/src/bundle.js
> +      svelte(),
same here not all vizzes require svettle plugin

2020-12-03 16:26 UTC, curran commented on packages/presenters/src/svelte.js
> +        if (!e.loc) e.loc = {};
I'm curious what this `.loc` is all about. A comment here would be helpful, and maybe a URL in the comment if this was informed from some resource/discussion thread.

2020-12-03 16:26 UTC, curran commented on packages/presenters/src/bundle.js
> +import svelte from './svelte';
Agree. This should go behind a dynamic import, like we do with CodeMirror. The import should only be triggered if we detect an `App.svelte`. I'm curious what the bundle footprint is for this... I'm guessing many KBs as it includes

```js
import { createFilter } from 'rollup-pluginutils';
import { compile } from 'svelte/compiler';
```

2020-12-03 16:36 UTC, milafrerichs commented on packages/presenters/src/svelte.js
> +        if (!e.loc) e.loc = {};
I just copied the code from `bubleJSXOnly` but this is just for printing error messages.

2020-12-03 19:16 UTC, curran commented on packages/presenters/src/bundle.js
> +      svelte(),
Indeed - this plugin can be only added if `App.svelte` is detected.

2020-12-03 21:50 UTC, curran requested changes
Great progress so far!

The second commit seems to have broken the test? When I run `npm test` locally in `presenters`, I get the following errors:

```
'svelte/internal' is imported by App.svelte, but could not be resolved – treating it as an external dependency
No name was provided for external module 'svelte/internal' in output.globals – guessing 'internal'
```
and
```
      + expected - actual

       [
         {
           "name": "bundle.js"
      -    "text": "var bundle = (function (internal) {\n\t'use strict';\n\n\t/* code.svelte generated by Svelte v3.31.0 */\n\n\tconst { console: console_1 } = internal.globals;\n\n\tfunction create_fragment(ctx) {\n\t\tconst block = {\n\t\t\tc: internal.noop,\n\t\t\tl: function claim(nodes) {\n\t\t\t\tthrow new Error(\"options.hydrate only works if the component was compiled with the `hydratable: true` option\");\n\t\t\t},\n\t\t\tm: internal.noop,\n\t\t\tp: internal.noop,\n\t\t\ti: internal.noop,\n\t\t\to: internal.noop,\n\t\t\td: internal.noop\n\t\t};\n\n\t\tinternal.dispatch_dev(\"SvelteRegisterBlock\", {\n\t\t\tblock,\n\t\t\tid: create_fragment.name,\n\t\t\ttype: \"component\",\n\t\t\tsource: \"\",\n\t\t\tctx\n\t\t});\n\n\t\treturn block;\n\t}\n\n\tfunction instance($$self, $$props) {\n\t\tlet { $$slots: slots = {}, $$scope } = $$props;\n\t\tinternal.validate_slots(\"Code\", slots, []);\n\t\tconsole.log(foo);\n\t\tconst writable_props = [];\n\n\t\tObject.keys($$props).forEach(key => {\n\t\t\tif (!~writable_props.indexOf(key) && key.slice(0, 2) !== \"$$\") console_1.warn(`<Code> was created with unknown prop '${key}'`);\n\t\t});\n\n\t\treturn [];\n\t}\n\n\tclass Code extends internal.SvelteComponentDev {\n\t\tconstructor(options) {\n\t\t\tsuper(options);\n\t\t\tinternal.init(this, options, instance, create_fragment, internal.safe_not_equal, {});\n\n\t\t\tinternal.dispatch_dev(\"SvelteRegisterComponent\", {\n\t\t\t\tcomponent: this,\n\t\t\t\ttagName: \"Code\",\n\t\t\t\toptions,\n\t\t\t\tid: create_fragment.name\n\t\t\t});\n\t\t}\n\t}\n\n\tconst app = new Code({ target: document.body, });\n\n\treturn app;\n\n}(internal));\n"
      +    "text": "(function () {\n\t'use strict';\n\n\tconst foo = \"bar\";\n\n\tconsole.log(foo);\n\n}());\n"
         }
       ]
```

I wonder if the Rollup `transform` function is allowed to be async? Not sure... That would be my first guess - maybe it's expecting a synchronous function.

Looking forward to seeing this land!

2020-12-03 21:50 UTC, curran commented on packages/presenters/src/svelte.js
> +  let {compile } = await import('svelte/compiler');
@milafrerichs Please prefer `const` over `let` if there is no reassignment. Thanks!
```suggestion
  const {compile } = await import('svelte/compiler');
```

2020-12-03 21:50 UTC, curran commented on packages/presenters/src/svelte.js
> +  var filter = createFilter(options.include, options.exclude);
```suggestion
  const filter = createFilter(options.include, options.exclude);
```

2020-12-03 21:50 UTC, curran commented on packages/presenters/src/bundle.js
> +      svelte(),
@milafrerichs Thanks for making the import dynamic!

However, that only gets us half way there, because due to this line here, the `svelte` plugin is _always_ invoked, even if there is no `App.svelte` present. Meaning, the dynamic import will _always_ load the additional bundle, even when it's not required.

Please add some logic that checks for the presence of `App.svelte`, then only include this in the `plugins` array if that file is present. That way, the dynamic import will _not_ trigger loading of the additional JS if there is no Svelte source code. Thanks!

2020-12-03 21:52 UTC, curran commented
Oh and another thing - please run `npm run prettier` (in the presenter package) to process all the source files with Prettier. Thanks!

2020-12-03 22:23 UTC, curran commented
Surfacing some Slack discussion:

Re: build sizes, yes - I wonder if the +136.73 KB is due to the Svelte compiler. It's hard to tell from these `npm run build` reports. The best way would be to create the production build, host it locally, then open up a viz page with the editor open, and see in the Network tab how many KB of JavaScript is fetched in total. The number can be compared across branches.

Re: comment in more detail - I may be wrong about it. My thinking was that the dynamic import would trigger even when no `.svelte` files are present, however, on closer reading, I see that transform short circuits if the file does not end with `.svelte` , so it seems it does the right thing actually right now. The "right thing" is:
 * If you load a viz page with the editor open that does not have any `App.svelte`, the Svelte compiler dynamic import should not trigger.
 * If you load a viz page with the editor open that does have an `App.svelte`, the Svelte compiler dynamic import should trigger.

It should be possible to test this out easily if I put this on staging... We could just look at the Network tab total JS for two different vizzes, one with App.svelte and one without. There should be more JS loaded if there is App.svelte.

2020-12-03 22:31 UTC, curran commented
Deployed this branch to Staging just now: https://staging.vizhub.com/

Trying it out in the editor https://staging.vizhub.com/curran/2db71d53e8a44ac5a3056638ef5cfd12?edit=files&file=App.svelte&line

It appears that `bundle.js` is not generated, after introducing `App.svelte` via the editor. There may be some logic that checks for `index.js` to enable Rollup. That may need to be expanded to detect `App.svelte`.

See `packages/neoFrontend/src/pages/VizPage/RunContext/updateBundleIfNeeded.js`

2020-12-03 22:40 UTC, curran commented
@milafrerichs I made a PR that, when merged, will go into this branch and enable Rollup when `App.svelte` is present. Please review and merge into here if you approve. Thanks!

https://github.com/curran/vizhub/pull/395

2020-12-03 22:41 UTC, milafrerichs commented
> It appears that `bundle.js` is not generated, after introducing `App.svelte` via the editor. There may be some logic that checks for `index.js` to enable Rollup. That may need to be expanded to detect `App.svelte`.
> 
> See `packages/neoFrontend/src/pages/VizPage/RunContext/updateBundleIfNeeded.js`

You always need an `index.js` anyway for svelte.
Take a look at their starter package: https://github.com/sveltejs/template
Maybe we can generate that for our users in the long run. 
If you include the following it will work:

```js
import App from './App.svelte'; 

const app = new App({ target: document.body, }); 

export default app;
```

see this example: https://staging.vizhub.com/milafrerichs/700cdab4dbff41c5a07038c4597c1db3?edit=files&file=bundle.js&line

2020-12-03 22:43 UTC, curran commented
Oh I see!!! Thanks.

2020-12-03 22:44 UTC, curran commented
So that PR I made just now is not valid actually... Closing.

2020-12-03 22:47 UTC, curran commented
Getting there! Now I see `index.js:3 Uncaught ReferenceError: internal is not defined`.

![image](https://user-images.githubusercontent.com/68416/101097698-a8971080-358f-11eb-8109-3a8222ed52b0.png)

2020-12-03 22:51 UTC, milafrerichs commented
> Getting there! Now I see `index.js:3 Uncaught ReferenceError: internal is not defined`.

yeah, saw that as well. I assume it's trying to use svelte which is actually not there yet ;) 
The imports do not work. this was just to get it to compile into js which it does :)

2020-12-03 23:52 UTC, curran commented
Maybe we need this, or something like this https://unpkg.com/svelte@3.0.1/internal.js

2020-12-03 23:58 UTC, curran commented
Possibly a good idea from Slack discussion:

```
globals: { ...vizhubLibraries, 'svelte': 'svelte', 'svelte/internal': 'svelte'},
```

Not sure where that came from, but maybe makes sense. We need a `svelte` global somehow, not sure where to get that.

2020-12-04 07:28 UTC, milafrerichs commented
it works 🎉

<img width="1572" alt="Bildschirmfoto 2020-12-04 um 08 27 35" src="https://user-images.githubusercontent.com/688980/101134439-a625cc80-360a-11eb-9745-c485957fe19c.png">
<img width="339" alt="Bildschirmfoto 2020-12-04 um 08 28 28" src="https://user-images.githubusercontent.com/688980/101134467-b473e880-360a-11eb-99ca-e7ae1acea62f.png">

2020-12-04 23:48 UTC, curran approved these changes
Looking great!

Can you please re-review this @stushurik ? Thanks!

2020-12-04 23:48 UTC, curran commented on packages/presenters/src/bundle.js
> +import svelte from './svelte';
Previous thread on this is resolved.

2020-12-04 23:48 UTC, curran commented on packages/presenters/src/bundle.js
> +      svelte(),
Previous thread on this is resolved.

2020-12-04 23:48 UTC, curran commented on packages/presenters/src/svelte.js
> +const SVELTE_URL = 'https://unpkg.com/svelte';
Might we want to use a specific version here? I think this will resolve to the latest, which is fine until a breaking change comes along (if ever).

2020-12-04 23:48 UTC, curran commented on packages/presenters/src/svelte.js
> +        format: 'esm',
Curious why format is 'esm' here.

2020-12-04 23:48 UTC, curran commented on packages/presenters/src/svelte.js
> +function fetch_if_uncached(url) {
Naming is inconsistent with the rest of the codebase. Ideally use camel case.
```suggestion
function fetchIfUncached(url) {
```

Please do a search & replace
 * `fetch_cache` --> `fetchCache`
 * `fetch_if_uncached` --> `fetchIfUncached`

Thanks!

2020-12-04 23:48 UTC, curran commented on packages/presenters/src/svelte.js
> +      if (resolved.startsWith(`https://`)) {
What case does this cover? Is this allowing `import` from URLs?

2020-12-04 23:48 UTC, curran commented on packages/presenters/test/test.js
> +global.fetch = sinon.fake.resolves({ ok: true, url: '', text: () => Promise.resolve("const globals={};const noop={};const dispatch_dev={};const validate_slots={};const SvelteComponentDev={};const ini
Any way to avoid the really long lines?

2020-12-04 23:51 UTC, curran commented on packages/presenters/src/svelte.js
> +      if (resolved.startsWith(`https://`)) {
Maybe best to keep it minimal, for only the immediate cases we're going to support.

I suggest to comment out (but keep around for future reference) any logic that's not strictly required for the Hello World to work.

2020-12-07 16:21 UTC, stushurik approved these changes

2020-12-07 16:21 UTC, stushurik commented on packages/presenters/src/bundle.js
> +      svelte(),
Now it looks ok, but if we will add more and more compilers (e.g. tsc) this place would grow

2020-12-07 16:21 UTC, stushurik commented on packages/presenters/src/svelte.js
> +const SVELTE_URL = 'https://unpkg.com/svelte';
agree, better to lock to some specific version

2020-12-08 09:20 UTC, milafrerichs commented on packages/presenters/src/svelte.js
> +        format: 'esm',
the alternative is `cjs` then you need to use commonjs for your code as well. 
the default is `esm`. I removed all those options because they're the default.

2020-12-08 12:32 UTC, curran approved these changes
Amazing!

2020-12-08 12:32 UTC, curran commented on packages/presenters/src/svelte.js
> +      if (resolved.startsWith(SVELTE_URL)) {
Nice! This is much more clear.

2020-12-08 12:43 UTC, curran commented
Looking into this failing test:

```

  1) Presenters
       Svelte
         should bundle files using Rollup:
     Error: 'SvelteComponent' is not exported by https://unpkg.com/svelte@3.31.0/internal/index.mjs, imported by App.svelte

```

2020-12-08 12:46 UTC, curran commented
Confirming that the tests pass on the previous commit f70405414f2938da6f3b0c9b6b6645f67cde0da2

2020-12-08 12:52 UTC, curran commented on packages/presenters/src/svelte.js
> +      if (resolved.startsWith(SVELTE_URL)) {
Could it actually be `resolved === SVELTE_URL`?

2020-12-08 12:59 UTC, merged