[WORK IN PROGRESS] experimental dynamic generation of globals
vizhub-studio/vizhub-legacy pull request #420
Opened 2020-12-20 15:51 UTC by stushurik

2020-12-20 15:53 UTC, stushurik commented
This PR contains a feature that uploads and introspects module from the dependencies list and generates a global name.

I tried it on the next package.json:
![image](https://user-images.githubusercontent.com/3383021/102717636-3a22b400-42ec-11eb-86c9-3300a8efa6ea.png)

2020-12-20 20:32 UTC, curran approved these changes
It's amazing that this works!

This is a bit "heavyweight" in that
 * it introduces use of `eval` in VizHub (which is generally dangerous security-wise), and
 * it introduces an additional network request as part of the build step (which may be cached - worth looking into the caching).

I was thinking, what if we track the same data that `vizhub-libraries` does _in the VizHub database_? Then we could consult that static data, and only if it's missing information about a certain library, we can use this technique to derive the name of the browser global.

It might even make sense to do this in some sort of more sandboxed environment, like an iFrame or something server-side.

This is very very interesting!

2020-12-20 20:32 UTC, curran commented on packages/presenters/src/bundle.js
> +        'self', 'globalThis',
TIL https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

I think this can only ever be a very limited set of things, including `window` also.

```suggestion
        'self', 'globalThis', 'window',
```

Also check this out https://gist.github.com/coolaj86/1870267

Apparently `["parent", "top", "frames", "self", "window"]` are all global aliases.

2020-12-20 20:34 UTC, curran commented
Tracked the D3 `globalThis` usage back to Rollup: https://github.com/rollup/rollup/pull/3691

Since this is from Rollup, it's probably fairly widespread.

2020-12-20 21:23 UTC, stushurik commented
@curran actually its not an eval, its Function constructor, mdn suggest it as safer and more performant alternative

2020-12-20 21:26 UTC, stushurik commented
@curran additional request is not a problem, cause it app would make it anyway -- when dependency would be injected as script tag. So it even make some kind of "prefetch" -- when browser would make request caused by script tag, package would be already in cache

2020-12-20 21:28 UTC, stushurik commented
@curran and vizhub-libraries might contain stale data

2020-12-20 21:31 UTC, stushurik commented
@curran As fast performance improvement I can imagine that we can store parsed data in local storage and maybe do parsing in webworkers

2020-12-21 12:41 UTC, curran requested changes
It is unfortunate that this PR contains a mix of Phase I (make the simplest solution work) and Phase II (experiment with automatically deriving globals).

Could you please split this up into 2 different PRs? One should just have the `path` implementation, and also the manually configurable `global` idea (`libraries[pkg].global`), and the other should contain the experimental stuff. Thanks!

2020-12-21 12:41 UTC, curran commented on packages/presenters/src/bundle.js
> +        const path = libraries[pkg] ? libraries[pkg].path || '' : '';
@stushurik This is a nice implementation of the `path` idea. Maybe could also add the `global` idea implementation here as well?

2021-12-03 18:21 UTC, closed without merging